### ISSUE TITLE
I can not run it

### ISSUE THREAD

**Issue by ByteYIFFF** [amazingyyc/SiftySifty#1]

**Comment by amazingyyc** [comment]
the project is build by cmake, and your pc must have installed the opencv for test Demo

**Comment by Hbelief** [comment]
> the project is build by cmake, and your pc must have installed the opencv for test Demo

yeah，my pc has been installed the opencv3.4 and its contrib ，but vs tells  it can not opencv some Source File.So your  program is Complete?

**Comment by Hbelief** [comment]
> the project is build by cmake, and your pc must have installed the opencv for test Demo

yeah，my pc has been installed the opencv3.4 and its contrib ，but vs tells me that it can not open some Source File.So your program is Complete?

**Comment by Hbelief** [comment]
> the project is build by cmake, and your pc must have installed the opencv for test Demo

yeah，my pc has  installed the opencv3.4 and its contrib ，but vs tells it can not opencv some Source File.So your program is Complete?

**Comment by ByteYIFFF** [comment]
> the project is build by cmake, and your pc must have installed the opencv for test Demo

yeah，my pc has installed the opencv3.4 and its contrib ，but vs tells me that it can not open some Source File.So your program is Complete?

**Comment by amazingyyc** [comment]
please attached the error info.

**Comment by amazingyyc** [comment]
> > the project is build by cmake, and your pc must have installed the opencv for test Demo
> 
> yeah，my pc has installed the opencv3.4 and its contrib ，but vs tells me that it can not open some Source File.So your program is Complete?

and the file is complete, u can see it in cmakelist.txt

**Comment by Hbelief** [comment]
> and the file is complete, u can see it in cmakelist.txt

![default](https://user-images.githubusercontent.com/38746426/49692846-e2023480-fb9e-11e8-86eb-0aedc4eefdf2.jpg)
    
i need cmake the program before  running it？

**Comment by amazingyyc** [comment]
u can find the siftysiftytest.h file in include folder.

I know 2 way that the VS run cmake project.
1: use the VS to import a cmake project. (must vs 2017+)
2:use cmd get into the project folder, run command:
`mkdir build`
`cd build`
`cmake ..`

than in build folder u can find a vs project, open it.

**Comment by ByteYIFFF** [comment]
thank U ，my brother
